name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build the Spring Boot jar
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Compute image tag (branch + short SHA)
      - name: Compute image tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG="${GITHUB_REF_NAME}-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/order-microservice-app:${IMAGE_TAG} .
            

      # 7. Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/order-microservice-app:${IMAGE_TAG}

      # 8. Install kustomize
      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/   

      # 9. Checkout Platform GitOps repo
      - name: Checkout Platform-Shared-Service repo
        uses: actions/checkout@v4
        with:
          repository: khoslak/Platform-Shared-Service
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      # 10. Update image tag in dev overlay
      - name: Update image tag in dev kustomization
        run: |
          cd gitops/apps/order-microservice/overlays/dev
          kustomize edit set image \
            ${{ secrets.DOCKER_USERNAME }}/order-microservice-app:${IMAGE_TAG}

      # 11. Commit and push GitOps change
      - name: Commit and push GitOps change
        run: |
          cd gitops
          git config user.name "platform-ci"
          git config user.email "platform-ci@users.noreply.github.com"

          git add apps/order-microservice/overlays/dev/kustomization.yaml
          git commit -m "order-microservice(dev): deploy ${IMAGE_TAG}"
          git push
